version: '3'

volumes:
  todo:

services:
  todo:
    image: 'postgres:latest'
    container_name: 'todo'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgrespw'
      - 'POSTGRES_DB=db_todo'
    volumes:
      - todo:/var/lib/postgresql/data
  crud:
    container_name: 'crud'
    image: 'crud'
    build:
      context: ./
      dockerfile: 'crud-microservice/Dockerfile'
    environment:
      - JAVA_OPTS=-Xmx512M
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo:5432/db_todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespw
    ports:
      - "8080:8080"
    restart: on-failure

