version: '3'

volumes:
  todo:

services:
  todo:
    image: 'postgres:latest'
    container_name: 'todo'
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}'
      - 'POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}'
      - 'POSTGRES_DB=db_todo'
    volumes:
      - todo:/var/lib/postgresql/data
  crud:
    container_name: 'crud'
    image: 'crud'
    build:
      context: ./
      dockerfile: 'crud-microservice/Dockerfile'
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx512M
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo:5432/db_todo
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    restart: on-failure

  telegram-bot:
    container_name: 'telegram-bot'
    image: 'telegram-bot'
    build:
      context: ./
      dockerfile: 'tgbot-microservice/Dockerfile'
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx512M
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - TODO_API_URL=${TODO_API_URL}
    ports:
      - "8081:8081"
    restart: on-failure

